#!/bin/bash

echo "VUE_APP_FIREBASE_API_KEY=${VUE_APP_FIREBASE_API_KEY}" >> .env.local
echo "VUE_APP_FIREBASE_AUTH_DOMAIN=${VUE_APP_FIREBASE_AUTH_DOMAIN}" >> .env.local
echo "VUE_APP_FIREBASE_PROJECT_ID=${VUE_APP_FIREBASE_PROJECT_ID}" >> .env.local
echo "VUE_APP_FIREBASE_STORAGE_BUCKET=${VUE_APP_FIREBASE_STORAGE_BUCKET}" >> .env.local
echo "VUE_APP_FIREBASE_MESSAGING_SENDER_ID=${VUE_APP_FIREBASE_MESSAGING_SENDER_ID}" >> .env.local
echo "VUE_APP_FIREBASE_APP_ID=${VUE_APP_FIREBASE_APP_ID}" >> .env.local
echo "VUE_APP_FIREBASE_DATABASE_URL=${VUE_APP_FIREBASE_DATABASE_URL}" >> .env.local
